name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: salman-khan1
          outputs: dist/snake.svg

      - name: Push the snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/snake.svg"
